### ISSUE TITLE
move Tortoise code into Tortoise repo

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/Tortoise#40]
@TheBizzle and I are working on this. our rough plan is:
- [x] Seth: cherry-pick any changes to core code from `tortoise` branch onto `headless` branch (#502)
- [x] Jason: have main repo publish test classes and files as an artifact so Tortoise can use them too (#503)
- [x] Seth: move the tortoise-only files and directories into the Tortoise repo, preserving the commit history
- [x] Seth: get Tortoise itself building and running by depending on NetLogoHeadless.jar retrieved from the CCL server by URL with SHA
- [x] Seth: get Tortoise tests passing by depending on NetLogoHeadlessTests.jar retrieved from the CCL server by URL with SHA
- [x] Seth: set up Travis build for new repo at https://travis-ci.org/NetLogo/Tortoise
- [x] Seth: attempt to slim down the history in the Tortoise repo (see http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository/)
