### ISSUE TITLE
improve NetLogo —> Tortoise —> Teletortoise publishing workflow

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/Tortoise#42]
finishing up the NetLogo/Tortoise repo split:
- [x] Jason?: publish the Tortoise engine and Tortoise compiler as jars (one jar or two, whichever seems easiest)
- [x] Jason?: use the new jars from the Teletortoise repo

that's the basics, but it isn't the whole story, because it leaves us with our usual awkward, unsatisfactory workflow of manually uploading jars to the CCL server. so then we need to decide:
- [ ] switch to git-subtree? and/or submodules? and/or sbt subprojects? and/or figure out a different development workflow involving automating things more using sbt? and/or bintray?
- [ ] at some point we might want to split the Tortoise compiler and Tortoise engine into separate repos, instead of having them together. since our ambition is for the Tortoise engine to eventually be usable directly from JS and from alt-JS languages.
